[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ousia = { path = "../ousia" }
gtk = { version = "0.7.3", package = "gtk4" }
rxrust = "1.0.0-beta.6"